-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE gambit.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  actor_id uuid,
  actor_role USER-DEFINED,
  company_id uuid,
  action text NOT NULL,
  target_type text,
  target_id uuid,
  details jsonb,
  ip_address inet,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES gambit.users(id),
  CONSTRAINT audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id)
);
CREATE TABLE gambit.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::gambit.company_status,
  warning_message text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE gambit.documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  fleet_id uuid,
  folder text NOT NULL,
  title text NOT NULL,
  file_path text,
  expiry_date date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'valid'::gambit.doc_status,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT documents_fleet_id_fkey FOREIGN KEY (fleet_id) REFERENCES gambit.fleet(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.drivers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  user_id uuid,
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  gender character CHECK (gender = ANY (ARRAY['M'::bpchar, 'F'::bpchar])),
  dob date,
  id_number text,
  passport_number text,
  license_number text NOT NULL,
  phone text,
  home_address text,
  status USER-DEFINED NOT NULL DEFAULT 'available'::gambit.driver_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES gambit.users(id),
  CONSTRAINT drivers_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.fleet (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  reg_number text NOT NULL,
  vehicle_type text NOT NULL,
  model text,
  year integer,
  engine_number text,
  chassis_number text,
  color text,
  gvm_kg numeric,
  nvm_kg numeric,
  status USER-DEFINED NOT NULL DEFAULT 'idle'::gambit.fleet_status,
  acquired_at date,
  disposed_at date,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fleet_pkey PRIMARY KEY (id),
  CONSTRAINT fleet_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT fleet_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.fuel_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  station_id uuid NOT NULL,
  fleet_id uuid,
  trip_id uuid,
  quantity_litres numeric NOT NULL,
  rate_per_litre numeric,
  total_cost numeric DEFAULT (quantity_litres * rate_per_litre),
  fuel_type text,
  odo_reading numeric,
  ordered_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fuel_orders_pkey PRIMARY KEY (id),
  CONSTRAINT fuel_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT fuel_orders_station_id_fkey FOREIGN KEY (station_id) REFERENCES gambit.fueling_stations(id),
  CONSTRAINT fuel_orders_fleet_id_fkey FOREIGN KEY (fleet_id) REFERENCES gambit.fleet(id),
  CONSTRAINT fuel_orders_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES gambit.trips(id),
  CONSTRAINT fuel_orders_ordered_by_fkey FOREIGN KEY (ordered_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.fueling_stations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  email text,
  phone text,
  fuel_type text NOT NULL CHECK (fuel_type = ANY (ARRAY['Diesel'::text, 'Petrol'::text, 'Blend'::text])),
  account_balance numeric DEFAULT 0,
  currency text DEFAULT 'USD'::text,
  vendor text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fueling_stations_pkey PRIMARY KEY (id),
  CONSTRAINT fueling_stations_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id)
);
CREATE TABLE gambit.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  unit text NOT NULL DEFAULT 'Pcs'::text,
  quantity numeric NOT NULL DEFAULT 0 CHECK (quantity >= 0::numeric),
  reorder_level numeric DEFAULT 3,
  unit_rate numeric,
  vendor text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.inventory_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  inventory_id uuid NOT NULL,
  trip_id uuid,
  move_type USER-DEFINED NOT NULL,
  quantity numeric NOT NULL,
  note text,
  actioned_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT inventory_movements_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES gambit.inventory(id),
  CONSTRAINT inventory_movements_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES gambit.trips(id),
  CONSTRAINT inventory_movements_actioned_by_fkey FOREIGN KEY (actioned_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  invoice_number text NOT NULL,
  trip_id uuid,
  customer_name text NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  total numeric DEFAULT (subtotal + tax_amount),
  amount_paid numeric NOT NULL DEFAULT 0,
  amount_due numeric DEFAULT ((subtotal + tax_amount) - amount_paid),
  currency text DEFAULT 'USD'::text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::gambit.invoice_status,
  due_date date,
  notes text,
  created_by uuid,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT invoices_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES gambit.trips(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id),
  CONSTRAINT invoices_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  device_info text,
  ip_address inet,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  revoked_at timestamp with time zone,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  reference text NOT NULL,
  trip_type text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::gambit.trip_status,
  horse_id uuid,
  driver_id uuid,
  transporter text,
  broker text,
  origin text NOT NULL,
  destination text NOT NULL,
  route_description text,
  cargo_type text,
  cargo_description text,
  tonnage numeric,
  freight_rate numeric,
  currency text DEFAULT 'USD'::text,
  start_date date,
  end_date date,
  driver_notes jsonb DEFAULT '{"route_map": false, "pod_number": null, "route_plan": false, "signed_pod": false, "odo_reading": null, "quantity_loaded": null, "loading_confirmed": false, "loading_instruction": false, "weighbridge_loading": null, "route_risk_assessment": false, "weighbridge_offloading": null}'::jsonb,
  truck_stop text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT trips_horse_id_fkey FOREIGN KEY (horse_id) REFERENCES gambit.fleet(id),
  CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES gambit.drivers(id),
  CONSTRAINT trips_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.tyres (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  fleet_id uuid,
  serial_number text,
  brand text,
  width_mm integer,
  aspect_ratio integer,
  diameter_in integer,
  tyre_type text,
  thread_depth numeric,
  lifespan_km numeric,
  current_km numeric DEFAULT 0,
  is_worn boolean DEFAULT false,
  vendor text,
  unit_rate numeric,
  purchased_at date,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tyres_pkey PRIMARY KEY (id),
  CONSTRAINT tyres_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT tyres_fleet_id_fkey FOREIGN KEY (fleet_id) REFERENCES gambit.fleet(id),
  CONSTRAINT tyres_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);
CREATE TABLE gambit.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'user'::gambit.user_role,
  full_name text,
  phone text,
  recovery_email text UNIQUE,
  email_verified boolean DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  must_change_pw boolean NOT NULL DEFAULT true,
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_company_id_fkey FOREIGN KEY (company_id) REFERENCES gambit.companies(id),
  CONSTRAINT users_created_by_fkey FOREIGN KEY (created_by) REFERENCES gambit.users(id)
);